image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get && go build ./... && go test ./...
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    command: ./nlp_text_classifier
