image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get && go build ./... && go test ./...
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data && go build && ./nlp_text_classifier.exe
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-browser
